DROP TABLE IF EXISTS bronze.account;
CREATE TABLE bronze.account (
	POLICY_NUMBER INT,
	PLAN_CODE INT,
	CLIENT_CODE INT,
	SUM_ASSURED FLOAT,
	MODAL_PREMIUM INT,
	ISSUE_DATE TIMESTAMP,
	TYPE VARCHAR(50),
	POLICY_STATUS VARCHAR(50),
	SURRENDER_DATE TIMESTAMP,
	PAYMENT_MODE INT
);

DROP TABLE IF EXISTS bronze.customer;
CREATE TABLE bronze.customer (
	CLIENT_CODE INT,
	AGE VARCHAR(50),
	MARITAL_STATUS VARCHAR(50),
	GENDER VARCHAR(50),
	INCOME INT,
	POSTCODE INT,
	LASTUPDATE DATE
);