DROP VIEW IF EXISTS gold.fact_account CASCADE;
CREATE VIEW gold.fact_account AS
SELECT POLICY_NUMBER,PLAN_CODE,CLIENT_CODE,SUM_ASSURED,MODAL_PREMIUM,
ISSUE_DATE,
EXTRACT (YEAR FROM ISSUE_DATE) AS issue_date_year,
TO_CHAR(ISSUE_DATE, 'Month') AS issue_date_month,
TYPE,POLICY_STATUS,
SURRENDER_DATE,
EXTRACT (YEAR FROM SURRENDER_DATE) AS surrender_date_year,
TO_CHAR(SURRENDER_DATE, 'Month') AS surrender_date_month,
PAYMENT_MODE
FROM silver.account;

DROP VIEW IF EXISTS gold.dim_customer CASCADE;
CREATE VIEW gold.dim_customer AS
SELECT CLIENT_CODE,AGE,MARITAL_STATUS,GENDER,INCOME,POSTCODE,
LASTUPDATE,
EXTRACT (YEAR FROM LASTUPDATE) AS LASTUPDATE_YEAR,
TO_CHAR(LASTUPDATE, 'Month') AS LASTUPDATE_MONTH
FROM silver.customer;