INSERT INTO silver.customer (
	CLIENT_CODE,AGE,MARITAL_STATUS,GENDER,INCOME,POSTCODE,LASTUPDATE
)
SELECT CLIENT_CODE,
AGE,
CASE UPPER(TRIM(MARITAL_STATUS))
	WHEN 'D' THEN 'Divorced'
	WHEN 'M' THEN 'Married'
	WHEN 'R' THEN 'Remarried'
	WHEN 'S' THEN 'Single'
	WHEN 'W' THEN 'Widowed'
	ELSE 'N/A'
END AS MARITAL_STATUS,
CASE UPPER(TRIM(GENDER))
	WHEN 'F' THEN 'Female'
	WHEN 'M' THEN 'Male'
ELSE 'N/A'
END AS GENDER,
INCOME,
POSTCODE,
LASTUPDATE
FROM (
	SELECT *, ROW_NUMBER() OVER (PARTITION BY client_code ORDER BY lastupdate DESC) AS flag_last FROM bronze.customer
)t 
WHERE flag_last = 1;


INSERT INTO silver.account(
	POLICY_NUMBER,PLAN_CODE,CLIENT_CODE,SUM_ASSURED,MODAL_PREMIUM,ISSUE_DATE,TYPE,POLICY_STATUS,SURRENDER_DATE,PAYMENT_MODE
)
SELECT POLICY_NUMBER,PLAN_CODE,CLIENT_CODE,SUM_ASSURED,MODAL_PREMIUM,ISSUE_DATE,TYPE,POLICY_STATUS,SURRENDER_DATE,PAYMENT_MODE
FROM bronze.account;
