DROP TABLE IF EXISTS silver.account;
CREATE TABLE silver.account (
	POLICY_NUMBER INT,
	PLAN_CODE INT,
	CLIENT_CODE INT,
	SUM_ASSURED FLOAT,
	MODAL_PREMIUM INT,
	ISSUE_DATE DATE,
	TYPE VARCHAR(50),
	POLICY_STATUS VARCHAR(50),
	SURRENDER_DATE DATE,
	PAYMENT_MODE INT,
	DWH_CREATE_DATE TIMESTAMP DEFAULT NOW()
);

DROP TABLE IF EXISTS silver.customer;
CREATE TABLE silver.customer (
	CLIENT_CODE INT,
	AGE VARCHAR(50),
	MARITAL_STATUS VARCHAR(50),
	GENDER VARCHAR(50),
	INCOME INT,
	POSTCODE INT,
	LASTUPDATE DATE,
	DWH_CREATE_DATE TIMESTAMP DEFAULT NOW()
);